# Update manually
ENVTEST_K8S_VERSION=1.34.0
SETUP_ENVTEST_VERSION := e8e550fd891562b7fdc5bf5d4dcf1d44f26d3905# v0.22.5
METRICS_SERVER_VERSION := 0.8.1

# Automatically updated with `make maintenance`.
GH_VERSION := 2.89.0
YQ_VERSION := 4.52.5
