apiVersion: v1
kind: Pod
metadata:
  namespace: monitoring
  name: observer-pod
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
  containers:
    - name: test
      image: quay.io/cybozu/ubuntu:20.04
      command: ["pause"]