apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: test-pod
  finalizers:
    - kubernetes
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
  containers:
    - name: foo
      image: quay.io/cybozu/ubuntu:20.04
      command: ["pause"]